name: CI

on:
  push:
    branches:
      - main 
    pull_request:
      branches:
          - '*'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: playground
          POSTGRES_USER: playground
          POSTGRES_DB: playground_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
