name: CI

on:
  push:
    branches:
      - main 
    pull_request:
      branches:
          - '*'

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL
      run: |
        brew install postgresql
        brew services start postgresql
    - name: Setup PostgreSQL
      run: |
        make db
    - name: Run tests
      run: make test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: playground
          POSTGRES_USER: playground
          POSTGRES_DB: playground_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
