name: CI

on:
  push:
    branches:
      - main 
    pull_request:
      branches:
          - '*'

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL
      run: |
        brew install postgresql
        brew services start postgresql
    - name: Setup PostgreSQL
      run: |
        make db
    - name: Run swift tests
      run: make test-swift
    - name: Upload coverage to Codecov.
      run: bash <(curl -s https://codecov.io/bash) -X xcodellvm -J -t ${{ secrets.CODE_COV_TOKEN }} -v

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
