name: CI

on:
  push:
    branches:
      - main 
    pull_request:
      branches:
          - '*'

jobs:
  build:
    name: MacOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PostgreSQL
      run: |
        brew install postgresql
        brew services start postgresql
    - name: Setup PostgreSQL
      run: |
        make db
    - name: Run swift tests
      run: make test-swift
    - name: Xcode tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -scheme swift-web-playground-Package -enableCodeCoverage YES build test
    - name: Upload coverage to Codecov.
      uses: codecov/codecov-actions@v2
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        verbose: true

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make test-linux
